batch_size: 64
height: 50
learning_rate: 0.001
max_text_length: 5
model_path: /content/drive/MyDrive/train_captcha/vcb/Models/vcb/202312311625
train_epochs: 2000
train_workers: 100
vocab: 4BZY0U1J2X3G865A79H
width: 155
